name: Liquid-Haskell-examples
# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
ghc-options: -fplugin=LiquidHaskell -fplugin-opt=LiquidHaskell:--counter-examples


dependencies:
  - liquidhaskell
  - liquidhaskell-boot
  - liquid-prelude
  - liquid-vector
  - base
  - containers
  - vector
  - liquid-fixpoint
  - mtl
  - ghc
  - ghc-paths

library:
  source-dirs:
    - Examples
